### ISSUE TITLE
[Feature Request] Support Tensors ?

### ISSUE THREAD

**Issue by BambOoxX** [apache/arrow-julia#433] opened 2023-05-02 14:00 UTC
I see in the documentation that there is currently no support of tensors.
I tried to check why it was so, but could not find a previous discussion about this. 
Is it still not planned ?

If I can be of help (not sure I can do much though) please tell me where I could start.

**Comment by Moelf** [comment] 2023-05-03 15:29
isn't it just dense n-dimensional array? have you tried? since Julia supports n-d array natively I don't imagine there's anything super special

**Comment by BambOoxX** [comment] 2023-05-03 16:09
Yes I guess it is just n-dimensional arrays, but these seem to be called tensors in the Arrow vocabulary. 
I don't think there should be anything fancy about this either, however it does (as advertised) not work. 

As an example, doing 
```julia
using Arrow
mat = rand(10,20,30)
Arrow.write("foo.bar",(mat=mat,)) # does not work
Arrow.write("foo.bar",(vec=mat[:,1,1],)) # works
```

**Comment by Moelf** [comment] 2023-05-03 18:34
```julia
Arrow.write("foo.bar",(mat=mat,)) # does not work
```
this doesn't make sense, your column needs to be a collection, it can't be a single tensor.

- - -
I tried
```julia
Arrow.write("foo.bar",(mat=[mat],))
```
and it works in terms to successfully written to disk, but the shape information is lost.

**Comment by BambOoxX** [comment] 2023-05-03 21:20
> ```julia
> Arrow.write("foo.bar",(mat=mat,)) # does not work
> ```
> this doesn't make sense, your column needs to be a collection, it can't be a single tensor.

Ah yes my bad, in a way I think I misunderstood the Arrow format capabilities. But now I get the point

**Comment by quinnj** [comment] 2023-06-09 03:45
Duplicate of #187

**Closed by quinnj** 2023-06-09 03:45 UTC
